# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2384700fae5bb90767bf84e0596b19897f438d9b330d59becf7ca715d977c7506ae14c36ddd339e9dbd245defe2dc2fefc190b482abd58d6b9400bd898990298

test:
  secret_key_base: d910f3d10b3dd630e14b38326c3843020e5c7d316d65da058d7de5d6dc679e23624cd58c717d95bfc2eb41360b9c0102d07b5c8a85532752b3dd643969684060

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
